# Generated by Django 3.0.7 on 2021-03-18 13:20

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/team/%Y/')),
                ('description', ckeditor.fields.RichTextField()),
                ('createddate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
