# Generated by Django 3.0.7 on 2021-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='photo',
            field=models.ImageField(upload_to='media/magazine/%Y/'),
        ),
    ]
