# Generated by Django 3.0.7 on 2021-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210318_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='photo',
            field=models.ImageField(upload_to='magazine/'),
        ),
    ]
