# Generated by Django 3.0.7 on 2021-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210318_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('need', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/post/%Y/')),
            ],
        ),
    ]
