# Generated by Django 3.0.7 on 2021-06-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_check'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='check',
            new_name='checkavl',
        ),
    ]
