# Generated by Django 3.0.7 on 2021-06-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210601_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkavl',
            name='photo',
            field=models.ImageField(upload_to='media/magazine/'),
        ),
    ]
