# Generated by Django 3.0.7 on 2021-06-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210602_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkavl',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
