# Generated by Django 3.0.7 on 2021-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20210617_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
