# Generated by Django 3.0.7 on 2021-06-17 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20210617_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='createddate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
